### ISSUE TITLE
How can i use it in JDK1.8?

### ISSUE THREAD

**Issue by kagg886** [markozajc/Akiwrapper#18]
I want to use it on Tomcat 9
but my ability can't let me to use it umm...

**Comment by markozajc** [comment]
I have migrated Akiwrapper to Java 11 in version 1.5. The last release that supported Java 1.8 was [1.4.3.1](https://github.com/markozajc/Akiwrapper/releases/tag/v1.4.3.1), but I doubt it still works considering the many breaking changes Akinator has done in their API. You're going to have to either use Java 11 or above, or backport the fixes from the latest release to 1.4.3.1 if you want proper Java 1.8 support.
