### ISSUE TITLE
Russian servers throw KO - SERVER DOWN

### ISSUE THREAD

**Issue by AndreyVyalov** [markozajc/Akiwrapper#5]
Last couple of days Russian servers throw KO - SERVER DOWN (seems like they totally don't work). Is there a way to fix it somehow?

**Comment by markozajc** [comment]
The servers have moved to `srv1-11.akinator.com`. I will update the server list ASAP, probably tomorrow.
Sorry for any inconvenience caused!

**Comment by AndreyVyalov** [comment]
Thanks a lot!

**Comment by markozajc** [comment]
The issue has been fixed in 1.3.4.
