### ISSUE TITLE
AkiwrapperBuilder...build() does not return

### ISSUE THREAD

**Issue by JackNova** [markozajc/Akiwrapper#8]
Hi Mark, I noticed that in this last version (1.3.4.5) the game does not start. Sorry but I did not have the opportunity to dig the issue further.

**Comment by markozajc** [comment]
I am currently looking into this issue and it so far seems to be an issue on Akinator's end, however I am not 100% positive.

**Comment by markozajc** [comment]
Fixed in 1.3.4.6 . If the fix doesn't persist, this issue will be opened again.

**Comment by JackNova** [comment]
your fix worked for me, thanks
