### ISSUE TITLE
Russian servier is down (KO - SERVER DOWN (RUSSIAN))

### ISSUE THREAD

**Issue by AndreyVyalov** [markozajc/Akiwrapper#9]
Looks like server links has changed

**Comment by markozajc** [comment]
Investigating the issue.

**Comment by markozajc** [comment]
The issue seems to affect more server groups, but not all. I have thus decided to scrap the old way of building a server list in favor of a more automated one.

**Comment by markozajc** [comment]
Assigned #10 to this issue

**Comment by markozajc** [comment]
Should be fixed in v1.4 .
